/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public int sum(int x, int y) {
    return x + y;
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
